import os
import json
import pandas as pd
import google.generativeai as genai
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

api_key = os.getenv("GEMINI_API_KEY")
if not api_key:
    raise ValueError("GEMINI_API_KEY not found in .env file")

genai.configure(api_key=api_key)

# --- CRITICAL FIX: USE A LOWER-THROUGHPUT MODEL TO AVOID RATE LIMITS ---
# Changed from "gemini-2.5-flash" to the lighter variant to reduce quota pressure
MODEL_NAME = "gemini-2.5-flash-lite"
# Fallback option if the above model is not available in this project/account
FALLBACK_MODEL = "gemini-2.0-flash-lite-preview"

def generate_theme_summary(theme_name, reviews):
    """
    Asks AI to summarize specific issues for a theme.
    """
    # Combine reviews into a single text block
    review_text = "\n".join([f"- {r}" for r in reviews])
    
    prompt = f"""
    You are a Product Manager at Groww.
    Analyze these user reviews about '{theme_name}'.
    Summarize the top 3 specific complaints or requests in 2 sentences.
    Do not use generic phrases. Be specific.
    
    Reviews:
    {review_text}
    """
    
    tried_fallback = False
    current_model = MODEL_NAME
    while True:
        try:
            model = genai.GenerativeModel(current_model)
            response = model.generate_content(prompt)
            return response.text.strip()
        except Exception as e:
            err_str = str(e).lower()
            # If model not found or unsupported, try fallback once
            if (not tried_fallback) and ("not found" in err_str or "not supported" in err_str or "404" in err_str):
                tried_fallback = True
                current_model = FALLBACK_MODEL
                print(f"Model {MODEL_NAME} not available; retrying with fallback model {FALLBACK_MODEL}...")
                continue
            return f"Could not generate summary due to error: {e}"

def generate_html_report(pulse_data):
    """
    Converts the JSON data into a nice HTML email body.
    """
    html = f"""
    <html>
    <body>
        <h2 style="color: #2E86C1;">{pulse_data['title']}</h2>
        <p><b>Executive Summary:</b> {pulse_data['executive_summary']}</p>
        <hr>
        <h3>🔥 Top Issues this Week</h3>
    """
    
    for item in pulse_data['top_themes']:
        html += f"""
        <div style="margin-bottom: 20px; padding: 10px; background-color: #f9f9f9; border-left: 4px solid #e74c3c;">
            <h4 style="margin: 0;">#{item['rank']} {item['theme_name']}</h4>
            <p style="margin: 5px 0;">{item['issue_summary']}</p>
        </div>
        """
        
    html += """
        <p style="font-size: 12px; color: #7f8c8d;">Generated by Automated Review Intelligence Pipeline</p>
    </body>
    </html>
    """
    return html

def generate_report(input_csv):
    print(f"--- Layer 3: Generating Weekly Pulse Report from {input_csv} ---")
    
    if not os.path.exists(input_csv):
        print("Error: Classified file not found.")
        return None

    df = pd.read_csv(input_csv)
    
    # Check for the column (handling both naming conventions)
    if 'operational_bucket' not in df.columns:
        if 'classification' in df.columns:
            df['operational_bucket'] = df['classification']
        else:
            print("❌ Critical Error: No classification column found.")
            return None

    # Filter out 'General Sentiment'
    actionable_df = df[df['operational_bucket'] != 'General Sentiment']
    
    if actionable_df.empty:
        print("No actionable reviews found. Using all data...")
        actionable_df = df

    # Group by theme and find Top 3
    theme_counts = actionable_df['operational_bucket'].value_counts()
    top_3_themes = theme_counts.head(3).index.tolist()
    
    print(f"Identified Top 3 Themes: {top_3_themes}")
    
    report_data = {
        "title": "Groww App: Weekly Product Pulse",
        "executive_summary": f"Analyzed {len(df)} recent reviews. Top issues are in {', '.join(top_3_themes)}.",
        "top_themes": []
    }
    
    # Loop through the themes to generate insights
    for i, theme in enumerate(top_3_themes):
        print(f"   Generating insights for: {theme}...")
        
        # Get reviews for this theme
        theme_reviews = df[df['operational_bucket'] == theme]['content'].tolist()
        
        # Limit to 10 reviews to save speed/quota
        summary = generate_theme_summary(theme, theme_reviews[:10])
        
        report_data['top_themes'].append({
            "rank": i + 1,
            "theme_name": theme,
            "issue_summary": summary
        })

    print("✅ Content Generation completed.")
    
    # --- CRITICAL FIX: Return HTML String ---
    # This prevents the 'dict object has no attribute encode' error in Step 4
    return generate_html_report(report_data)

if __name__ == "__main__":
    # Test run
    print(generate_report("weekly_classified.csv"))